### ISSUE TITLE
_round_primal_to_bounds does not respect solver tolerances

### ISSUE THREAD

**Issue by cdiener** [biosustain/optlang#106]
## Reproduce:

- Create any model and set a variable upper bound very large (for instance 1e6) and maximize that variable.
- try to get the primal_values and observe the error

## Problem:

`_round_primal_to_bounds` uses its own absolute tolerance of 1e-5 but the solvers usually use a relative and absolute tolerance around 1e-9. For the case of large upper bounds the solver tolerance will be rtol*ub + atol which is 1e-9 * 1e6 + 1e-9 ~ 1e-3 > 1e-5. However the solution is completely feasible given the set solver tolerances. 

`_round_primal_to_bounds` should either respect the solver tolerances or simply not check bounds feasibility since this is done by all lower level solver interfaces anyways.

**Comment by KristianJensen** [comment]
Hi.
We are aware of this issue, but it's probably about time we do something about it :) I'm leaning towards not checking the bounds. Do you see any downsides with that?

@phantomas1234 What was the reason this was added in the first place?

**Comment by cdiener** [comment]
Nope, I don't see any downsides. Most solvers are pretty strict with that anyways and I think no solver will declare a solution "optimal" if it violates bounds.

Thanks for getting to that :smile:

**Comment by matthiaskoenig** [comment]
I would support not checking the bounds.
The current round to primals is slowing down getting the primals from the
solver, because instead of just returning the primals vector provided by
the solver, optlang iterates over all variables and rounds the primals for
each variable individually. If the rounding is not necessary it should be
dropped.
