### ISSUE TITLE
implement esolver support

### ISSUE THREAD

**Issue by hredestig** [biosustain/optlang#113]
[esolver](http://www.dii.uchile.cl/~daespino/ESolver_doc/main.html) is an exact solver and cobrapy currently supports an interface to solve metabolic models using it. Since we are shifting to only using optlang interfaces in cobrapy, I raise this issue to help people comment and upvote this issue if they feel they would benefit from esolver in optlang as well.

**Comment by cdiener** [comment]
Does optlang support exact LPs for glpk? There are some nice features there as well. For instance converting a float basis to an exact one which is faster than computing *de novo*.

**Comment by zakandrewking** [comment]
Esolver is important for the reasons given by Ali in this 2015 commentary (for anyone who hasn't seen it):

http://msb.embopress.org/content/11/10/831

We use it in the BiGG Models model validator to provide more accurate validation, so for that application esolver support is important.

**Comment by cdiener** [comment]
@zakandrewking what is the advantage of using esolver over other exact solver like GLPK's `glp_exact` which also uses exact rational algebra via GMP?

**Comment by zakandrewking** [comment]
Any exact solver is good (in theory). I'm not sure about the specific differences between those two.

**Comment by cdiener** [comment]
@zakandrewking ok, definitely agree with that :+1:

**Comment by KristianJensen** [comment]
I'm closing this issue as GLPK's `glp_exact` method is now implemented in the `glpk_exact_interface`. If anyone has a specific wish for esolver support, feel free to open another issue.
