### ISSUE TITLE
float values output for integer variables

### ISSUE THREAD

**Issue by matejsebo** [biosustain/optlang#118]
When formulating a problem with Variable objects of type integer, optimized outputted values for those variables are returned as floating point representations of the integer results. Is this behavior expected (as opposed to outputting integer values)?
Thanks! 
~ Matej

**Comment by KristianJensen** [comment]
Hi and thanks for the question. Intuitively it would make sense that the primals of integer variables be returned as integer types. However, the numerical solvers still treat integer variables as floats with a small tolerance on their integrality. Thus it sometimes happens that the primal of an integer variable is not a whole number, e.g. 2.0, but rather 1.9999, where the difference between the two numbers is still within the allowed tolerance. Depending on the application, this small difference can have an impact on the behaviour of the model. To allow the users to see when this is happening we have chosen not to round the primals when they are returned from the solver.

If you experience integer variables that deviate enough from integer values to affect the model behaviour you can reduce the integrality tolerance through `model.configuration.tolerances`.

I hope this answers your question :)
