### ISSUE TITLE
Binary variables cannot be fixed using bounds

### ISSUE THREAD

**Issue by psalvy** [biosustain/optlang#130]
Good day optlang people !

I stumbled upon something that I might call an issue, but it might as well be a design choice from your side. I use MILPs, which contain binary variables. Sometimes, I need to constrain my model by assigning the value of the binary variable to either 1, or 0. However, in [`optlang.interface`](https://github.com/biosustain/optlang/blob/master/optlang/interface.py), lines 111-134, the methods `__test_valid_lower_bound` and `__test_valid_upper_bound` forbid such a thing by throwing a `ValueError`.

So far, my fix has been to use integer variables in the stead of binary variables, but I fear it might have an impact on the solver behavior, as some heuristics are specifically tailored to binary problems.

What say you, would it be a design choice or a small issue to fix ?

(That being said, I really love your software!)
Cheers,
Pierre

**Comment by KristianJensen** [comment]
Hi

Thanks for the issue report (and the nice words)!
I agree that what you describe is not optimal behaviour. I myself have actually also been using integer variables to circumvent this, but you are right that this could indeed cost some performance.
I'll look into a fix for this :)

**Comment by KristianJensen** [comment]
I've pushed a fix. It turns out it was only `__test_valid_lower_bound` and `__test_valid_upper_bound` that prevented it.

**Comment by psalvy** [comment]
Wow, pretty fast ! Thanks again !
