### ISSUE TITLE
[feature request] exact solver for GLPK

### ISSUE THREAD

**Issue by cdiener** [biosustain/optlang#141]
GLPK provides an exact solver and even allows that one to use a non-exact prior basis which could be a good strategy to get an exact solution quickly. This would be a pretty helpful feature for many user I think.

**Comment by KristianJensen** [comment]
Is it really possible to find an exact solution using a non-exact basis? Or will it also find an exact basis from a non-exact starting point?

**Comment by cdiener** [comment]
From the GLPK docs:

> Computations in exact arithmetic are very time consuming, so solving LP
problem with the routine glp_exact from the very beginning is not a good
idea. It is much better at first to find an optimal basis with the routine
glp_simplex and only then to call glp_exact, in which case only a few
simplex iterations need to be performed in exact arithmetic.

So I would guess it does allow finding an exact basis from an inexact one.
