### ISSUE TITLE
Model with spaces in constraint names not copied directly with GLPK

### ISSUE THREAD

**Issue by cdiener** [biosustain/optlang#154]
See https://github.com/opencobra/cobrapy/issues/690. 

Seems that something is off during serializing the `Model` object and re-reading it. Since GLPK serializes using .lp files I suspect the problem lies there (maybe you can not have variable or constraint names in LP files?).

**Comment by KristianJensen** [comment]
Ideally I think we should handle ID's differently where we assign arbitrary internal glpk ID's and keep track of the actual names displayed to the user. We had the same problem with #138

**Comment by Midnighter** [comment]
Spaces are already forbidden for variables so I don't see it as a big problem. And actually SBML doesn't allow spaces in the `id` attribute.

**Comment by cdiener** [comment]
I would also be fine to not allow those.

**Comment by KristianJensen** [comment]
This should now be fixed, and will be released in 1.4.1
