### ISSUE TITLE
GLPK objects cannot be pickled

### ISSUE THREAD

**Issue by taylo5jm** [biosustain/optlang#188]
Hi all,

It seems that GLPK objects cannot be pickled. For example, I set the tolerance of a solver object and pickled it. After reading the pickle, I found the tolerance is set to the default value (1e-07). 

Based on the discussion and code implemented for #123, I believe this might be due to the fact that the tolerances in the GLPK interface contain lambda functions (https://github.com/biosustain/optlang/blob/8da74d1a5c590699e92378d321e4926779b1712c/optlang/glpk_interface.py#L439-L453). 

Here is a code chunk that uses cobrapy and a SBML model from BiGG to instantiate a solver for testing purposes. I am using optlang version 1.4.3, Python 3.7, and Mac OS X 10.13.6.

```
model = read_sbml_model('data/models/RECON1.xml')
solver = model.solver
type(solver)
solver.configuration.tolerances.feasibility
solver.configuration.tolerances.feasibility = 1e-05
import pickle
with open('solver.p', 'wb') as fp:
    pickle.dump(solver, fp)

with open('solver.p', 'rb') as fp:
    solver = pickle.load(fp)

solver.configuration.tolerances.feasibility # should be 1e-05, but is 1e-07
```

**Comment by cdiener** [comment]
Yep, same problem as with gurobi before (https://github.com/biosustain/optlang/pull/124). Seems like a regression since that definitely worked before. I can port the Gurobi fix to GLPK if desired...

**Comment by taylo5jm** [comment]
Christian, it would be great if the Gurobi fix could be ported to GLPK. I can write some tests for pickling.
