### ISSUE TITLE
Unexpected behaviour with glpk_interface

### ISSUE THREAD

**Issue by tariq-a** [biosustain/optlang#194]
I'm running into some unexpected behaviour when re-using a model to optimise different objectives. Here is a simple example which reproduces the issue:

```python
from optlang.glpk_interface import Variable, Constraint, Objective, Model

x1 = Variable('x1')
x2 = Variable('x2')
x3 = Variable('x3')

c1 = Constraint(x1, lb=90, ub=90)
c2 = Constraint(x2, lb=0, ub=float('inf'))
c3 = Constraint(x3, lb=0, ub=float('inf'))

m1 = Model(variables=[x1, x2, x3], constraints=[c1, c2, c3])
m1.objective = Objective(x2, direction='max')
m1.optimize()
print("x2 max: {}".format(m1.objective.value))
m1.objective = Objective(x3, direction='min')
m1.optimize()
print("x3 min: {}".format(m1.objective.value))
m2 = Model(variables=[x1, x2, x3], constraints=[c1, c2, c3])
m2.objective = Objective(x3, direction='min')
m2.optimize()
print("x3 min: {}".format(m2.objective.value))
```
The output of this is:
x2 max: inf
x3 min: nan
x3 min: 0.0
I would have expected:
x2 max: inf
x3 min: 0.0
x3 min: 0.0

Have I forgotten some step between optimisations of m1 which resets the model?

**Comment by Midnighter** [comment]
Two things:

1. `float("inf")` is not fully supported. The accepted way to not bound a direction is to set it to `None`.
2. You should always check the status of your solution.

Applying those two changes,

```python
c2 = Constraint(x2, lb=0, ub=None)
c3 = Constraint(x3, lb=0, ub=None)

# ...

print(m1.status)
```

you get:

```
unbounded
x2 max: 0.0
optimal
x3 min: 0.0
optimal
x3 min: 0.0
```

which is what I would expect. Feel free to re-open the issue if this doesn't solve your problem.

**Comment by tariq-a** [comment]
Thanks for explaining this.
