### ISSUE TITLE
Problems with simple objective expressions

### ISSUE THREAD

**Issue by Midnighter** [biosustain/optlang#197]
(Originally reported by @eladnoor.)

Creating a single variable expression objective, as described in the following, produces a `ValueError` in the `_parse_quadratic_expression` check. This affects both the CPLEX and Gurobi interfaces but *not* the GLPK one.

Example:
```py
from optlang.cplex_interface import Model, Variable, Objective


model = Model(name="test")
g1 = Variable("g1")
model.add(g1)
model.objective = Objective(g1, direction='min', sloppy=True, name="o1")
```

Error:
```
Traceback (most recent call last):
  File "mre.py", line 8, in <module>
    model.objective = Objective(g1, direction='min', sloppy=True, name="o1")
  File "/home/moritz/.virtualenvs/cobrapie/lib/python3.6/site-packages/optlang/cplex_interface.py", line 728, in objective
    offset, linear_coefficients, quadratic_coeffients = parse_optimization_expression(value, quadratic=True, expression=expression)
  File "/home/moritz/.virtualenvs/cobrapie/lib/python3.6/site-packages/optlang/expression_parsing.py", line 59, in parse_optimization_expression
    offset, linear_coefficients, quadratic_coefficients = _parse_quadratic_expression(expression, **kwargs)
  File "/home/moritz/.virtualenvs/cobrapie/lib/python3.6/site-packages/optlang/expression_parsing.py", line 120, in _parse_quadratic_expression
    raise ValueError("Expression of type {} could not be parsed.".format(type(expression)))
ValueError: Expression of type <class 'optlang.cplex_interface.Variable'> could not be parsed.
```

A similar thing happens when the objective is the uniform sum of multiple variables.

```py
from optlang.symbolics import add


model = Model(name="test")
gammas = [Variable(f"g{i}") for i in range(3)]
model.add(gammas)
model.objective = Objective(add(gammas), direction='min', sloppy=True, name="g1")
```

I am aware of workarounds particularly based on `objective.set_linear_coefficients` but I believe these should be made to work. (GLPK doesn't include the quadratic expression check which is why it doesn't fail.)

**Comment by KristianJensen** [comment]
The issue arises from the use of the `sloppy=True` parameter when creating the objective. The `sloppy` parameter can be used in various places throughout optlang to bypass certain validity checks and normalisation procedures. This can sometimes result in significant speedups, but the catch is that all expressions, bounds, etc must be valid or the program will fail in unexpected ways.

For constructing objectives with `sloppy=True`, one requirement is that the expression must be a sympy expression of the form `c1 * x1 + c2 * x2 + ...` where c's are numerical coefficients and x's are `Variable` objects.
Setting `sloppy` be False in the examples above allows them both to run without error.

Unfortunately, the `sloppy` parameter is currently undocumented, and successful use of it requires quite detailed knowledge of the inner workings of optlang.

**Comment by Midnighter** [comment]
Sorry, I should have mentioned that yes we had been aware that `sloppy=False` solves the issue. My question is if we should make the expression checking code more flexible? Or is that exactly what the sloppy argument was meant for? Also it's annoying that `1 * x` is simplified to `x` and also triggers this.

**Comment by KristianJensen** [comment]
Sloppy was meant for internal use in optlang (to avoid double-checks) and for development of packages that tightly interconnect with optlang, where expression construction etc can be strictly controlled.

The average end-user is not meant to use `sloppy=True`, and the speedup is not significant in most use cases. With `sloppy=False` (default) everything is very flexible thanks to sympy, and basically all possible formulations of valid expressions should be accepted.

Regarding `1 * x`, this is caused by implicit sympy simplifications. Using `1.0 * x` instead should work.
