### ISSUE TITLE
Objective value not updated during optimize()

### ISSUE THREAD

**Issue by DWesl** [biosustain/optlang#200]
```python
from optlang import Variable, Model, Objective
var = Variable("a", ub=5)
obj = Objective(var, direction="max")
simple_model = Model(objective=obj, variables=var)
simple_model.optimize()
print(simple_model.objective.value, simple_model.primal_values)
```
has output
```
0.0 OrderedDict([('a', 5.0)])
```
where I would expect something closer to
```
5.0 OrderedDict([('a', 5.0)])
```
I am using Python 3.6.8, optlang 1.4.4, swiglpk 4.65.0, and GLPK 4.65 on Cygwin.
I ran the optlang test suite on my system before installing it, and recall failures related only to not having the test files in the PyPI tarball.  I could clone the repository and run the test suite again if you think that would help.

I am hoping that this is something simple wrong on my system, and fixing that will also fix problems with larger models I'm trying to work with.  Please let me know what else I should be checking into.

If it helps, I also have a recent scipy installed and simple_model.interface says it's using `optlang.glpk_interface`.  I really don't know what I'm missing here; any help would be appreciated.

**Comment by KristianJensen** [comment]
Hi.
I'm quite astonished that we have not noticed this bug before. Apparently the objective is not properly set when it is added inside the Model constructor, so you're effectively optimising with a zero objective, and the initial value for `var` happens to be 5 (or whatever `ub` you set).
I will try to fix this. In the meantime you can circumvent the bug by modifying your code to:
```
from optlang import Variable, Model, Objective
var = Variable("a", ub=5)
obj = Objective(var, direction="max")
simple_model = Model()
simple_model.add(var)  # Not strictly necessary in this case since setting the objective implicitly adds the required variables
simple_model.objective = obj
simple_model.optimize()
print(simple_model.objective.value, simple_model.primal_values)
```
Don't hesitate to write again if this does not work or you come across other strange bugs :)

**Comment by DWesl** [comment]
That worked for me.  Thank you.

**Comment by KristianJensen** [comment]
After inspecting the code I realized that the `Model.__init__` functionality needs substantial refactoring. Using the `variables` and `constraints` arguments will give similar problems. I will make a PR soon with a general fix for all the solver interfaces, but for now the Model constructor should only be called without arguments. Variables, constraints and objective should be added subsequently with the `add` method and `model.objective` setter, respectively.
These arguments are a remnant from an old version of the codebase and have not been intended to be used for a long time.

**Comment by DWesl** [comment]
That works.

Out of curiosity, is there an easy way to specify initial guesses for the primal_values dictionary or the user-created variables?  There are heuristics for generating feasible solutions for my problem, but I don't know how to tell the solver about them.  Would that be a matter of calling `model.primal_values.update` before calling `model.optimize` or assigning to variable.primal before adding it to the model? Or would I have to call the swiglpk bindings directly?

**Comment by KristianJensen** [comment]
Setting an initial feasible solution is not currently supported through the optlang interface, but if a given solver supports it, you can construct the problem with optlang and then set the initial solution directly through the native solver interface. You can access the solver-specific problem object through `model.problem`

**Comment by DWesl** [comment]
On 7/10/2019 4:39 AM, Kristian Jensen wrote:
> Setting an initial feasible solution is not currently supported through 
> the optlang interface, but if a given solver supports it, you can 
> construct the problem with optlang and then set the initial solution 
> directly through the native solver interface. You can access the 
> solver-specific problem object through |model.problem|
> 
Thanks for your reply.
