### ISSUE TITLE
Accumulation of tmp files (.sav)

### ISSUE THREAD

**Issue by caroenp** [biosustain/optlang#32]
Hello,

I started using cplex with cameo.py two month ago, and pickled a lot of objects. It seems that cplex_interface.py use the functions __getstate__ and __setstate__ to transfer a cplex problem to/from bites, creating temp files .sav in the process. But these .sav files are not deleted afterward and using cameo for two month get me 200 000 files. sav, taking a total space of 409 Go in my hard drive.

Unless I misunderstand the use of these temp files, you should probably erase them after use?

**Comment by KristianJensen** [comment]
Hello

Thank you for making us aware of this issue. The tempfiles are definitely not supposed to be kept and take up hard drive space. Usually the tempfiles are created in a location that is cleaned up by the OS periodically, but I can try to find out why this isn't happening or just make the functions delete them afterwards. Which OS are you running? And is it a long-running server that rarely gets rebooted?

**Comment by caroenp** [comment]
I run on Windows 7 Entreprise (french) 64 bit, and yes it's a long-running server that rarely gets rebooted.

**Comment by phantomas1234** [comment]
@caroenp Thanks for the report. I released optlang==0.6.0 that includes the fix from #33.
