### ISSUE TITLE
Swap sympy with symengine

### ISSUE THREAD

**Issue by phantomas1234** [biosustain/optlang#70]
It seems like symengine can be installed quite easily with conda now.

**Comment by KristianJensen** [comment]
I think it also has all the features we need now. I did some preliminary testing recently. It looks like construction of expressions for constraints and objectives are sped up by a factor of >100

**Comment by phantomas1234** [comment]
🚀 That sounds very promising!
I can't find the branch where I got like 80% of the way. It is probably still on my old laptop. I only found a very old branch from when symengine was still named csympy.

**Comment by KristianJensen** [comment]
New symengine release is finally out, so this should be ready soon
