### ISSUE TITLE
Gurobi can not solve MIP model

### ISSUE THREAD

**Issue by cdiener** [biosustain/optlang#74]
Hi,

the appended MIP problem solves fine with the glpk or cplex interface but is declared infeasible when using the gurobi interface. Tested Gurobi version was 7.02.

[Model in JSON (renamed to .txt for upload)](https://github.com/biosustain/optlang/files/804139/textbook_loopless.txt)

**Comment by KristianJensen** [comment]
I found and fixed a few bugs in the gurobi interface. I can now optimize the model to the same value as cplex.

**Comment by cdiener** [comment]
Thanks! :smile:
