### ISSUE TITLE
Use the new helper functions from swiglpk

### ISSUE THREAD

**Issue by cdiener** [biosustain/optlang#80]
Just to keep track: would be awesome if optlang would use the new helper functions from swiglpk to get primals/duals and create intArrays/doubleArrays. This should give some speed boost.

**Comment by cdiener** [comment]
Just saw that the helpers are not so helpful for optlang :/ Better wait and make swiglpk possibly return {name: val} dicts for primals and duals.

**Comment by KristianJensen** [comment]
For the iJO1366 model it reduces the time it takes to get primal values from ~18ms to ~10ms, which I think is a pretty good speedup. I'll change it in the near future.

It could be reduced even further to ~3.5ms if `.primal_values` could return a normal dict instead of an OrderedDict, which I personally wouldn't mind, but that would be a breaking change. I'm not sure how much of a practical difference it would make though.
For comparison, it takes 21ms with cplex and 29ms with gurobi.

**Comment by Midnighter** [comment]
Have you considered using a `pandas.Series`? It seems to me like upstream (cameo, cobra) both depend on pandas now anyway. Since the dictionary stores the variable names, the interface would be the same and in given order plus great ways to further use the `Series`.

**Comment by cdiener** [comment]
Yeah there is not much speed up if you have to iterate over variable names/indices again. Will send a PR to swiglpk to return dicts by default. 

Have you also tried the as_*Array functions? The should make some model creation steps faster since you don't have to iterate over the array anymore to set values.

**Comment by KristianJensen** [comment]
Optlang would still have to loop over the dict to ensure that the order is correct. Personally I don't really think further optimization of this step is worth the trouble. Do you have a specific scenario in mind where 10-20 ms for getting all primal values would be a major pain?

I haven't tried using the Array functions yet.

**Comment by Midnighter** [comment]
Just to reiterate: You don't like

```Python
return pandas.Series(index=self.variables, data=x.as_doubleArray)
```
because of the pandas dependency or because you cannot guarantee the order of either variables or the array helper?

**Comment by cdiener** [comment]
Hmm ok then. Yeah, unfortunately in many problems I have to solve getting the primal values is the bottle neck. For instance for flux sampling you generate initial search directions by individually maximizing each variable and storing all primals of this optimization. Here the actual optimization is much faster than getting the primals in each iteration. 

However, those are my use cases and they may not apply to a majority of users.

**Comment by KristianJensen** [comment]
Regarding pandas I don't think the extra dependency is justified by the little use I can see for it in optlang.

**Comment by KristianJensen** [comment]
@cdiener Maybe we could add a method along the lines of `primal_value_array` (not a very good name), that returns a list-like object. This could directly return the array from glpk avoiding any python object construction. I'll try to think about a good way to do this.

**Comment by cdiener** [comment]
I usually need the primal values together with the names. But I agree with you. It't not really a good idea to micro-optimize only a single interface. My motivation to change the swiglpk functions was more to make it easier to use for optlang, not to optimize speed *per sé*. But as I understand, for that to be the case the swiglpk functions would need to take the variable *names* as an argument and give the primals/duals exactly for that list, correct?

I think we are better off optimizing some code expressions in optlang later on, especially the ones doing object creation for Container. Sometimes you can gain quite a lot from substituting loops by comprehensions or constructing dict objects via zip. But that is something I can test myself and come back to you if I really find good options that don't make the code ugly :smile:

**Comment by matthiaskoenig** [comment]
@cdiener Have a look at #101 
the `model._get_variables_names` and `model._get_primal_values`
should give you fast access and works for different interfaces (at least found the vector functions for cplex and swiglpk). 
I mainly had the same issue with fast access to primals and this gives me speedups of ~50%.

**Comment by KristianJensen** [comment]
The last fix in swiglpk (returning the mip values when necessary) is not released yet, so I'm keeping this issue open to remind myself to release and fix this.
